version: '3.9'
services:
  db:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    volumes:
      - .:/myapp
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
    restart: on-failure
    stdin_open: true
    tty: true
